### ISSUE TITLE
waimai10k.csv可以分享一下吗？

### ISSUE THREAD

**Issue by Initzzh** [kangyangWHU/ML_Project#2]
博主，您好，我发现你的工程文件中是需要waimai10k.csv，请问，您可以分享一下吗？

**Comment by kangyangWHU** [comment]
我从这个网址获得的数据，但我已经把原始数据分为了训练、验证和测试，在data下。https://github.com/SophonPlus/ChineseNlpCorpus/blob/master/datasets/waimai_10k/intro.ipynb
